runtime: nodejs16

entrypoint: node index.js

env_variables:
  TELEGRAM_BOT_TOKEN: 6271327874:AAGyLQuMV80He6Uv-cTXCbmyOqNwFlXnV2I
  OPENAI_API_KEY: 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

instance_class: F1
automatic_scaling:
  min_instances: 1
  max_instances: 1
  cool_down_period_sec: 60
